/**
 * Option 4 — Multi-host scale-out via SSHFS over LAN.
 * Like Option 2 (NFS) but the share rides over SSH instead of NFS, so no
 * extra ports / firewall rules are needed beyond the existing sshd.
 *
 * Same role split: one "host" exposes a directory over sshd, all clients
 * mount it via FUSE/sshfs and run a gateway container.
 */

import { prompt, promptInt, promptYN, promptRequired, promptChoice, randomToken, c } from './prompts.js';
import { ensureOutputDir, writeOutput, renderEnv, detectLanIp } from './util.js';

export default async function run() {
    console.log(c.dim(
        'SSHFS topology. One host stores DuckLake files in a regular directory\n' +
        'and runs sshd. Other hosts mount that directory via sshfs and run\n' +
        'gateway containers. Postgres lives on the storage host too.\n'
    ));

    const role = await promptChoice(
        'Which role is THIS host?',
        [
            'catalog+storage  (runs Postgres + sshd; holds the canonical files)',
            'gateway-client   (mounts the remote dir via sshfs, runs the gateway)',
        ],
        1,
    );

    return role === 1 ? generateServer() : generateClient();
}

async function generateServer() {
    const lanIp     = await detectLanIp();
    const serverIp  = await promptRequired('LAN IP of THIS host (advertised to clients)', lanIp || '');
    const sshUser   = await prompt('Unix user that owns the share', 'ichibi');
    const sharePath = await prompt('Host directory to share', `/home/${sshUser}/ichibi-lake`);
    const apiKeyInput = await prompt('API key(s), comma-separated (blank = generate one)', '');
    const apiKeys   = apiKeyInput.trim() || `ICHIBI_LAKE_${randomToken(16)}`;
    const sqlRO     = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option4-sshfs-server');

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 4 — SSHFS over LAN, role = catalog+storage host.
#
# This host runs ONLY Postgres. The shared directory ${sharePath}
# is exposed via the host's existing sshd; nothing Docker-managed needed.

services:
  db:
    image: postgres:17
    container_name: superlake-postgres
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ducklake
    volumes:
      - ${sharePath}/postgres:/var/lib/postgresql/data
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
`;

    const setup = `#!/usr/bin/env bash
# setup-sshfs-server.sh — prepare the shared DuckLake directory.
# Run ONCE as root on the catalog+storage host. Idempotent.
set -euo pipefail

USER_NAME="${sshUser}"
SHARE="${sharePath}"

echo "==> Ensuring user '$USER_NAME' exists"
id -u "$USER_NAME" >/dev/null 2>&1 || useradd -m -s /bin/bash "$USER_NAME"

echo "==> Creating $SHARE/{ducklake,blobs,postgres}"
mkdir -p "$SHARE"/{ducklake,blobs,postgres}
chown -R "$USER_NAME":"$USER_NAME" "$SHARE/ducklake" "$SHARE/blobs"
chmod 0775 "$SHARE/ducklake" "$SHARE/blobs"

echo "==> Done."
echo "    From each client, append its public SSH key to:"
echo "    /home/$USER_NAME/.ssh/authorized_keys"
echo "    Then start the Postgres catalog:  docker compose up -d"
`;

    const envBody = renderEnv(
        { API_KEYS: apiKeys, SQL_READ_ONLY: String(sqlRO) },
        { API_KEYS: 'Distribute to every gateway-client .env',
          SQL_READ_ONLY: 'Catalog host does not run a gateway; informational only' },
        `SuperLake — Option 4 (SSHFS), catalog+storage host @ ${serverIp}`,
    );

    const readme = `# SuperLake — Option 4 (SSHFS): catalog + storage host

Holds the canonical \`${sharePath}\` directory and runs Postgres. Clients
mount the directory over sshd using FUSE/sshfs.

## Quick start

\`\`\`bash
sudo ./setup-sshfs-server.sh
docker compose up -d
\`\`\`

## Values to copy to every gateway-client

| Setting | Value |
|---|---|
| Catalog host LAN IP | \`${serverIp}\` |
| SSH user            | \`${sshUser}\` |
| Remote share path   | \`${sharePath}\` |
| Postgres port       | \`5432\` |
| API key(s)          | (see \`.env\`) |
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',          compose));
    files.push(await writeOutput(outDir, 'setup-sshfs-server.sh', setup, { executable: true }));
    files.push(await writeOutput(outDir, '.env',                  envBody));
    files.push(await writeOutput(outDir, 'README.md',             readme));

    return {
        outDir, files,
        nextSteps: [
            `cd ${outDir.rel}`,
            'sudo ./setup-sshfs-server.sh',
            'Add each client\'s SSH public key to authorized_keys',
            'docker compose up -d',
        ],
    };
}

async function generateClient() {
    const serverIp   = await promptRequired('LAN IP of the catalog+storage host', '');
    const sshUser    = await prompt('SSH user on the storage host', 'ichibi');
    const sharePath  = await prompt('Remote share path on the storage host', `/home/${sshUser}/ichibi-lake`);
    const mountPoint = await prompt('Local mount point on THIS host', '/mnt/ichibi-lake');
    const sshKey     = await prompt('Local SSH private key file', `${process.env.HOME || '/root'}/.ssh/id_ed25519`);
    const hostPort   = await promptInt('Host port for the gateway', 3333, { min: 1024, max: 60000 });
    const apiKeys    = await promptRequired('API key(s) (must match catalog host\'s .env)', '');
    const sqlRO      = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option4-sshfs-client');

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 4 — SSHFS, role = gateway-client.
#
# DuckLake catalog is on ${serverIp}:5432; data + blobs are bind-mounted
# from ${mountPoint} which itself is an sshfs mount of
# ${sshUser}@${serverIp}:${sharePath}. Run mount-sshfs.sh before "up".

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    container_name: superlake-app
    ports: ["${hostPort}:3000"]
    environment:
      - DUCKLAKE_PG_HOST=${serverIp}
      - DUCKLAKE_PG_PORT=5432
      - DUCKLAKE_PG_USER=postgres
      - DUCKLAKE_PG_PASSWORD=postgres
      - DUCKLAKE_PG_DB=ducklake
      - DUCKLAKE_DATA_PATH=/app/data_files
      - DUCKDB_ALLOW_COMMUNITY_EXTENSIONS=1
      - USE_FILESYSTEM_BLOBS=1
      - BLOBS_PATH=/app/blobs
      - API_KEYS=\${API_KEYS}
      - SQL_READ_ONLY=\${SQL_READ_ONLY:-true}
      - PORT=3000
    volumes:
      - ${mountPoint}/ducklake:/app/data_files
      - ${mountPoint}/blobs:/app/blobs
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/swagger.yaml > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
`;

    const mountScript = `#!/usr/bin/env bash
# mount-sshfs.sh — mount the remote DuckLake directory over SSH.
# Run ONCE as root on each gateway-client host. Idempotent.
set -euo pipefail

REMOTE_USER="${sshUser}"
REMOTE_HOST="${serverIp}"
REMOTE_PATH="${sharePath}"
MOUNT="${mountPoint}"
IDENTITY="${sshKey}"

echo "==> Installing sshfs"
if   command -v apt-get >/dev/null; then apt-get update && apt-get install -y sshfs
elif command -v dnf     >/dev/null; then dnf install -y fuse-sshfs
elif command -v yum     >/dev/null; then yum install -y fuse-sshfs
else echo "Install sshfs manually" >&2; exit 1
fi

echo "==> Creating mount point $MOUNT"
mkdir -p "$MOUNT"

echo "==> Adding /etc/fstab entry (passwordless via $IDENTITY)"
FSTAB="$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH  $MOUNT  fuse.sshfs  IdentityFile=$IDENTITY,_netdev,reconnect,allow_other,default_permissions,uid=1000,gid=1000  0  0"
grep -qxF "$FSTAB" /etc/fstab || echo "$FSTAB" >> /etc/fstab

echo "==> Mounting"
mountpoint -q "$MOUNT" || mount "$MOUNT"

echo "==> Done. Verify with:  ls -la $MOUNT/ducklake $MOUNT/blobs"
`;

    const envBody = renderEnv(
        { API_KEYS: apiKeys, SQL_READ_ONLY: String(sqlRO) },
        { API_KEYS: 'Must match the catalog host', SQL_READ_ONLY: 'Reject DDL/DML on /query etc.' },
        `SuperLake — Option 4 (SSHFS), gateway-client → ${serverIp}`,
    );

    const readme = `# SuperLake — Option 4 (SSHFS): gateway-client host

This host mounts \`${sshUser}@${serverIp}:${sharePath}\` over SSHFS at
\`${mountPoint}\` and runs one ichibi-lake gateway pointing at the
Postgres catalog on \`${serverIp}:5432\`.

## Prerequisites

- An SSH key pair already exists at \`${sshKey}\` (or edit \`mount-sshfs.sh\`).
- That key's public counterpart has been appended to
  \`/home/${sshUser}/.ssh/authorized_keys\` on the storage host.

## Quick start

\`\`\`bash
sudo ./mount-sshfs.sh             # one-time mount
docker compose up -d --build
\`\`\`

Gateway URL:  http://localhost:${hostPort}

## Verify it joined the lake

\`\`\`bash
curl http://localhost:${hostPort}/tables \\
  -H "x-api-key: $(grep -E '^API_KEYS=' .env | cut -d= -f2 | cut -d, -f1 | tr -d '\\"')"
\`\`\`
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',    compose));
    files.push(await writeOutput(outDir, 'mount-sshfs.sh',  mountScript, { executable: true }));
    files.push(await writeOutput(outDir, '.env',            envBody));
    files.push(await writeOutput(outDir, 'README.md',       readme));

    return {
        outDir, files,
        nextSteps: [
            `cd ${outDir.rel}`,
            'sudo ./mount-sshfs.sh',
            'docker compose up -d --build',
            `Then hit http://localhost:${hostPort}`,
        ],
    };
}
