/**
 * Option 3 — Multi-host scale-out via MinIO (self-hosted S3-compatible store).
 * One host runs Postgres (catalog) + MinIO (object storage). All other hosts
 * run gateway containers that talk S3 to MinIO and Postgres to the catalog.
 *
 * Requires a tiny patch to src/db.js so DuckLake writes Parquet to s3://...
 * The wizard emits the patch as docs/db-s3-patch.md inside the output dir.
 */

import { prompt, promptInt, promptYN, promptRequired, promptChoice, randomToken, c } from './prompts.js';
import { ensureOutputDir, writeOutput, renderEnv, detectLanIp } from './util.js';

export default async function run() {
    console.log(c.dim(
        'MinIO topology. One host runs Postgres + MinIO. Other hosts run\n' +
        'gateways that write Parquet via S3 to s3://<bucket>/ducklake.\n' +
        'Run this wizard once per host, picking the right role each time.\n'
    ));

    const role = await promptChoice(
        'Which role is THIS host?',
        [
            'catalog+storage  (runs Postgres + MinIO server)',
            'gateway-client   (runs the ichibi-lake gateway pointing at the catalog)',
        ],
        1,
    );

    return role === 1 ? generateServer() : generateClient();
}

function s3PatchDoc() {
    return `# Required patch to src/db.js for S3 / MinIO data path

DuckLake itself supports an \`s3://\` DATA_PATH out of the box, but the
gateway must register an S3 secret before the ATTACH so DuckDB knows the
endpoint + credentials of the MinIO server.

Insert the following block in \`src/db.js\`, **between** the existing
\`CREATE SECRET (TYPE ducklake, ...)\` call and the \`ATTACH 'ducklake:' ...\`
call:

\`\`\`js
// SuperLake / MinIO: register an S3 secret so DuckLake can write Parquet
// to s3://<bucket>/<prefix>. All values come from env vars set in compose.yaml.
if (process.env.S3_ENDPOINT) {
    const s3Endpoint = process.env.S3_ENDPOINT;                // host:port, no scheme
    const s3Region   = process.env.S3_REGION   || 'us-east-1';
    const s3Key      = process.env.S3_ACCESS_KEY;
    const s3Secret   = process.env.S3_SECRET_KEY;
    const s3UseSsl   = String(process.env.S3_USE_SSL ?? 'false').toLowerCase() === 'true';
    const s3PathStyle = String(process.env.S3_PATH_STYLE ?? 'true').toLowerCase() === 'true';
    await conn.run(\`
        CREATE SECRET s3_minio (
            TYPE s3,
            KEY_ID '\${s3Key}',
            SECRET '\${s3Secret}',
            REGION '\${s3Region}',
            ENDPOINT '\${s3Endpoint}',
            USE_SSL \${s3UseSsl},
            URL_STYLE '\${s3PathStyle ? 'path' : 'vhost'}'
        );
    \`);
}
\`\`\`

After applying the patch, set \`DUCKLAKE_DATA_PATH=s3://<bucket>/ducklake/\`
in the gateway environment (already done by the generated compose.yaml).
`;
}

async function generateServer() {
    const lanIp     = await detectLanIp();
    const serverIp  = await promptRequired('LAN IP of THIS host (advertised to clients)', lanIp || '');
    const bucket    = await prompt('S3 bucket name to create on startup', 'ichibi-lake');
    const accessKey = await prompt('MinIO root access key', 'ichibi-lake');
    const secretKey = await prompt('MinIO root secret key (blank = generate)', '');
    const finalSecret = secretKey || randomToken(20);
    const apiKeyInput = await prompt('API key(s) for the gateways (blank = generate)', '');
    const apiKeys   = apiKeyInput.trim() || `ICHIBI_LAKE_${randomToken(16)}`;
    const sqlRO     = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option3-minio-server');

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 3 — MinIO, role = catalog+storage host.

services:
  db:
    image: postgres:17
    container_name: superlake-postgres
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ducklake
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: superlake-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # web console
    environment:
      - MINIO_ROOT_USER=\${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=\${S3_SECRET_KEY}
    volumes:
      - ./data/minio:/data
    networks: [app-network]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  minio-init:
    image: quay.io/minio/mc:latest
    container_name: superlake-minio-init
    depends_on:
      minio:
        condition: service_healthy
    networks: [app-network]
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 \${S3_ACCESS_KEY} \${S3_SECRET_KEY} &&
        mc mb --ignore-existing local/\${S3_BUCKET} &&
        echo 'Bucket \${S3_BUCKET} ready.'
      "
    restart: "no"

networks:
  app-network:
    driver: bridge
`;

    const envBody = renderEnv(
        {
            API_KEYS:       apiKeys,
            SQL_READ_ONLY:  String(sqlRO),
            S3_BUCKET:      bucket,
            S3_ACCESS_KEY:  accessKey,
            S3_SECRET_KEY:  finalSecret,
        },
        {
            API_KEYS:      'Distribute to every gateway-client .env',
            S3_ACCESS_KEY: 'Distribute to every gateway-client .env',
            S3_SECRET_KEY: 'Distribute to every gateway-client .env',
        },
        `SuperLake — Option 3 (MinIO), catalog+storage host @ ${serverIp}`,
    );

    const readme = `# SuperLake — Option 3 (MinIO): catalog + storage host

This host runs **Postgres** (DuckLake catalog), **MinIO** (S3 storage), and a
one-shot \`minio-init\` container that creates the bucket.

## Quick start

\`\`\`bash
docker compose up -d
\`\`\`

| Service | URL |
|---|---|
| MinIO S3 API     | http://${serverIp}:9000 |
| MinIO web console| http://${serverIp}:9001 |
| Postgres         | ${serverIp}:5432 |

## Values to copy to every gateway-client

| Setting          | Value |
|---|---|
| Catalog host IP  | \`${serverIp}\` |
| S3 endpoint      | \`${serverIp}:9000\` |
| S3 bucket        | \`${bucket}\` |
| S3 access key    | \`${accessKey}\` |
| S3 secret key    | (see \`.env\`) |
| API key(s)       | (see \`.env\`) |

## Required code change

See \`db-s3-patch.md\` — \`src/db.js\` needs ~20 lines added to register the S3
secret with DuckDB before the DuckLake ATTACH. Apply once; affects every
host that runs the gateway.
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',    compose));
    files.push(await writeOutput(outDir, '.env',            envBody));
    files.push(await writeOutput(outDir, 'README.md',       readme));
    files.push(await writeOutput(outDir, 'db-s3-patch.md',  s3PatchDoc()));

    return {
        outDir, files,
        nextSteps: [
            `cd ${outDir.rel}`,
            'docker compose up -d',
            `Open the MinIO console at http://${serverIp}:9001 to verify the bucket`,
            'Apply db-s3-patch.md to src/db.js before starting any gateway-client',
        ],
    };
}

async function generateClient() {
    const serverIp     = await promptRequired('LAN IP of the catalog+MinIO host', '');
    const bucket       = await prompt('S3 bucket name (must match server)', 'ichibi-lake');
    const accessKey    = await promptRequired('S3 access key (must match server)', 'ichibi-lake');
    const secretKey    = await promptRequired('S3 secret key (must match server)', '');
    const hostPort     = await promptInt('Host port for the gateway', 3333, { min: 1024, max: 60000 });
    const apiKeys      = await promptRequired('API key(s) (must match catalog host\'s .env)', '');
    const sqlRO        = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option3-minio-client');

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 3 — MinIO, role = gateway-client.
#
# Requires the db-s3-patch.md changes to src/db.js. Catalog lives on
# ${serverIp}:5432; Parquet data is written to s3://${bucket}/ducklake.

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    container_name: superlake-app
    ports: ["${hostPort}:3000"]
    environment:
      - DUCKLAKE_PG_HOST=${serverIp}
      - DUCKLAKE_PG_PORT=5432
      - DUCKLAKE_PG_USER=postgres
      - DUCKLAKE_PG_PASSWORD=postgres
      - DUCKLAKE_PG_DB=ducklake
      - DUCKLAKE_DATA_PATH=s3://${bucket}/ducklake/
      - DUCKDB_ALLOW_COMMUNITY_EXTENSIONS=1
      # BLOBs cannot use the filesystem path with S3 — store inline in Parquet.
      - USE_FILESYSTEM_BLOBS=0
      - API_KEYS=\${API_KEYS}
      - SQL_READ_ONLY=\${SQL_READ_ONLY:-true}
      - PORT=3000
      # Consumed by the db-s3-patch.md changes in src/db.js
      - S3_ENDPOINT=${serverIp}:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=\${S3_ACCESS_KEY}
      - S3_SECRET_KEY=\${S3_SECRET_KEY}
      - S3_USE_SSL=false
      - S3_PATH_STYLE=true
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/swagger.yaml > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
`;

    const envBody = renderEnv(
        {
            API_KEYS:       apiKeys,
            SQL_READ_ONLY:  String(sqlRO),
            S3_ACCESS_KEY:  accessKey,
            S3_SECRET_KEY:  secretKey,
        },
        {
            API_KEYS:      'Must match the catalog host',
            S3_ACCESS_KEY: 'Must match the MinIO root user on the catalog host',
            S3_SECRET_KEY: 'Must match the MinIO root password on the catalog host',
        },
        `SuperLake — Option 3 (MinIO), gateway-client → ${serverIp}`,
    );

    const readme = `# SuperLake — Option 3 (MinIO): gateway-client host

This host runs one ichibi-lake gateway that:
- Reads/writes metadata against Postgres on \`${serverIp}:5432\`
- Reads/writes Parquet via S3 against MinIO at \`${serverIp}:9000\` (bucket \`${bucket}\`)

## Prerequisite — patch src/db.js once

See \`db-s3-patch.md\` (also in the option3-minio-server output dir). Without
this patch DuckDB does not know how to talk S3 to MinIO.

## Quick start

\`\`\`bash
docker compose up -d --build
\`\`\`

Gateway URL:  http://localhost:${hostPort}

## Verify the lake is shared

\`\`\`bash
curl http://localhost:${hostPort}/tables \\
  -H "x-api-key: $(grep -E '^API_KEYS=' .env | cut -d= -f2 | cut -d, -f1 | tr -d '\\"')"
\`\`\`

Tables written by any other gateway pointed at the same MinIO bucket should
appear here.
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',   compose));
    files.push(await writeOutput(outDir, '.env',           envBody));
    files.push(await writeOutput(outDir, 'README.md',      readme));
    files.push(await writeOutput(outDir, 'db-s3-patch.md', s3PatchDoc()));

    return {
        outDir, files,
        nextSteps: [
            `Apply db-s3-patch.md to src/db.js (if not already done)`,
            `cd ${outDir.rel}`,
            'docker compose up -d --build',
            `Then hit http://localhost:${hostPort}`,
        ],
    };
}
