/**
 * Option 2 — Multi-host scale-out via NFS over LAN.
 * One host runs Postgres + exports a shared directory; the other hosts run
 * gateway containers that bind-mount the NFS export as /app/data_files and
 * /app/blobs, and point DUCKLAKE_PG_HOST at the catalog host.
 *
 * The wizard is run once per host: pick the role, answer a few prompts,
 * then start the generated compose stack on that host.
 */

import { prompt, promptInt, promptYN, promptRequired, promptChoice, randomToken, c } from './prompts.js';
import { ensureOutputDir, writeOutput, renderEnv, detectLanIp } from './util.js';

export default async function run() {
    console.log(c.dim(
        'Multi-host NFS topology. One host plays "catalog+storage" (Postgres +\n' +
        'NFS server). All other hosts mount the NFS export and run gateways.\n' +
        'Run this wizard once per host, picking the right role each time.\n'
    ));

    const role = await promptChoice(
        'Which role is THIS host?',
        [
            'catalog+storage  (runs Postgres + exports /srv/ichibi-lake over NFS)',
            'gateway-client   (mounts NFS, runs the ichibi-lake gateway)',
        ],
        1,
    );

    return role === 1 ? generateServer() : generateClient();
}

async function generateServer() {
    const lanIp        = await detectLanIp();
    const serverIp     = await promptRequired('LAN IP of THIS host (advertised to clients)', lanIp || '');
    const clientSubnet = await prompt('Subnet allowed to mount the export (CIDR)', '192.168.0.0/16');
    const sharePath    = await prompt('Host directory to export', '/srv/ichibi-lake');
    const apiKeyInput  = await prompt('API key(s), comma-separated (blank = generate one)', '');
    const apiKeys      = apiKeyInput.trim() || `ICHIBI_LAKE_${randomToken(16)}`;
    const sqlRO        = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option2-nfs-server');

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 2 — NFS over LAN, role = catalog+storage host.
#
# This file runs ONLY Postgres (the shared DuckLake catalog). NFS itself is
# exported by the host OS, NOT by Docker — see setup-nfs-server.sh.

services:
  db:
    image: postgres:17
    container_name: superlake-postgres
    ports:
      - "5432:5432"          # exposed on the LAN for client gateways
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ducklake
    volumes:
      - ${sharePath}/postgres:/var/lib/postgresql/data
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
`;

    const setupNfs = `#!/usr/bin/env bash
# setup-nfs-server.sh — install + export the shared DuckLake directory.
# Run ONCE as root on the catalog+storage host. Idempotent.
set -euo pipefail

SHARE="${sharePath}"
SUBNET="${clientSubnet}"

echo "==> Installing NFS server packages"
if   command -v apt-get >/dev/null; then apt-get update && apt-get install -y nfs-kernel-server
elif command -v dnf     >/dev/null; then dnf install -y nfs-utils
elif command -v yum     >/dev/null; then yum install -y nfs-utils
else echo "Unknown package manager — install nfs-kernel-server / nfs-utils manually" >&2; exit 1
fi

echo "==> Creating $SHARE/{ducklake,blobs,postgres}"
mkdir -p "$SHARE"/{ducklake,blobs,postgres}
chown -R 1000:1000 "$SHARE/ducklake" "$SHARE/blobs"   # match the app container uid
chmod 0775 "$SHARE/ducklake" "$SHARE/blobs"

echo "==> Adding /etc/exports entry"
EXPORT_LINE="$SHARE $SUBNET(rw,sync,no_subtree_check,no_root_squash)"
grep -qxF "$EXPORT_LINE" /etc/exports || echo "$EXPORT_LINE" >> /etc/exports

echo "==> Reloading exports"
exportfs -ra
systemctl enable --now nfs-server 2>/dev/null || systemctl enable --now nfs-kernel-server

echo "==> Done. Verify with:  showmount -e ${serverIp}"
`;

    const envBody = renderEnv(
        { API_KEYS: apiKeys, SQL_READ_ONLY: String(sqlRO) },
        { API_KEYS: 'Distribute this value to every gateway-client .env',
          SQL_READ_ONLY: 'Catalog host does not run a gateway; informational only' },
        `SuperLake — Option 2 (NFS), catalog+storage host @ ${serverIp}`,
    );

    const readme = `# SuperLake — Option 2 (NFS): catalog + storage host

This host runs **Postgres** (DuckLake catalog) and **exports** \`${sharePath}\`
over NFS to the gateway clients on the LAN.

## Quick start

\`\`\`bash
sudo ./setup-nfs-server.sh        # one-time host setup (root)
docker compose up -d              # start the Postgres catalog
\`\`\`

## Values to copy to every gateway-client

| Setting | Value |
|---|---|
| Catalog host LAN IP | \`${serverIp}\` |
| Postgres port       | \`5432\` |
| NFS export path     | \`${sharePath}\` |
| Allowed subnet      | \`${clientSubnet}\` |
| API key(s)          | (see \`.env\`) |

## Verify

\`\`\`bash
showmount -e ${serverIp}
psql -h ${serverIp} -U postgres -d ducklake -c 'select 1'
\`\`\`
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',        compose));
    files.push(await writeOutput(outDir, 'setup-nfs-server.sh', setupNfs, { executable: true }));
    files.push(await writeOutput(outDir, '.env',                envBody));
    files.push(await writeOutput(outDir, 'README.md',           readme));

    return {
        outDir, files,
        nextSteps: [
            `cd ${outDir.rel}`,
            'sudo ./setup-nfs-server.sh',
            'docker compose up -d',
            `Then run the wizard on each gateway-client host using IP ${serverIp}`,
        ],
    };
}

async function generateClient() {
    const serverIp     = await promptRequired('LAN IP of the catalog+storage host', '');
    const sharePath    = await prompt('Remote NFS export path', '/srv/ichibi-lake');
    const mountPoint   = await prompt('Local mount point on THIS host', '/mnt/ichibi-lake');
    const hostPort     = await promptInt('Host port for the gateway', 3333, { min: 1024, max: 60000 });
    const includeKafka = await promptYN('Include a local Kafka broker?', false);
    const apiKeys      = await promptRequired('API key(s) (must match catalog host\'s .env)', '');
    const sqlRO        = await promptYN('Enforce SQL_READ_ONLY on user-supplied SQL endpoints?', true);

    const outDir = await ensureOutputDir('option2-nfs-client');

    const kafkaService = includeKafka ? `
  kafka:
    image: apache/kafka:4.3.1
    container_name: superlake-kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: superlake-cluster
    networks: [app-network]
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
` : '';
    const kafkaDep = includeKafka
        ? '\n      kafka:\n        condition: service_healthy'
        : '';
    const kafkaEnv = includeKafka ? 'kafka:9092' : '';

    const compose = `# superlake/${outDir.rel.split('/').pop()}/compose.yaml
# Generated by scripts/superlake-wizard.js
# Topology: Option 2 — NFS over LAN, role = gateway-client.
#
# DuckLake catalog lives on ${serverIp}:5432; data + blobs are bind-mounted
# from ${mountPoint} (which is itself an NFS mount of ${serverIp}:${sharePath}).
# Run setup-nfs-client.sh once on this host before "docker compose up".

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    container_name: superlake-app
    ports:
      - "${hostPort}:3000"
    environment:
      - DUCKLAKE_PG_HOST=${serverIp}
      - DUCKLAKE_PG_PORT=5432
      - DUCKLAKE_PG_USER=postgres
      - DUCKLAKE_PG_PASSWORD=postgres
      - DUCKLAKE_PG_DB=ducklake
      - DUCKLAKE_DATA_PATH=/app/data_files
      - DUCKDB_ALLOW_COMMUNITY_EXTENSIONS=1
      - USE_FILESYSTEM_BLOBS=1
      - BLOBS_PATH=/app/blobs
      - API_KEYS=\${API_KEYS}
      - SQL_READ_ONLY=\${SQL_READ_ONLY:-true}
      - KAFKA_BROKERS=${kafkaEnv}
      - PORT=3000
    volumes:
      - ${mountPoint}/ducklake:/app/data_files
      - ${mountPoint}/blobs:/app/blobs
    networks: [app-network]${kafkaDep ? '\n    depends_on:' + kafkaDep : ''}
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/swagger.yaml > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
${kafkaService}
networks:
  app-network:
    driver: bridge
`;

    const setupNfs = `#!/usr/bin/env bash
# setup-nfs-client.sh — mount the shared DuckLake export from ${serverIp}.
# Run ONCE as root on each gateway-client host. Idempotent.
set -euo pipefail

SERVER="${serverIp}"
REMOTE="${sharePath}"
MOUNT="${mountPoint}"

echo "==> Installing NFS client packages"
if   command -v apt-get >/dev/null; then apt-get update && apt-get install -y nfs-common
elif command -v dnf     >/dev/null; then dnf install -y nfs-utils
elif command -v yum     >/dev/null; then yum install -y nfs-utils
else echo "Install nfs-common / nfs-utils manually" >&2; exit 1
fi

echo "==> Creating mount point $MOUNT"
mkdir -p "$MOUNT"

echo "==> Adding /etc/fstab entry"
FSTAB="$SERVER:$REMOTE  $MOUNT  nfs  rw,hard,intr,_netdev,noatime  0  0"
grep -qxF "$FSTAB" /etc/fstab || echo "$FSTAB" >> /etc/fstab

echo "==> Mounting"
mountpoint -q "$MOUNT" || mount "$MOUNT"

echo "==> Done. Verify with:  ls -la $MOUNT/ducklake $MOUNT/blobs"
`;

    const envBody = renderEnv(
        { API_KEYS: apiKeys, SQL_READ_ONLY: String(sqlRO) },
        { API_KEYS: 'Must match the catalog host', SQL_READ_ONLY: 'Reject DDL/DML on /query etc.' },
        `SuperLake — Option 2 (NFS), gateway-client → ${serverIp}`,
    );

    const readme = `# SuperLake — Option 2 (NFS): gateway-client host

This host mounts the shared DuckLake export from \`${serverIp}:${sharePath}\`
at \`${mountPoint}\` and runs one ichibi-lake gateway container against the
catalog on \`${serverIp}:5432\`.

## Quick start

\`\`\`bash
sudo ./setup-nfs-client.sh        # one-time host mount (root)
docker compose up -d --build
\`\`\`

Gateway URL:  http://localhost:${hostPort}

## Verify it joined the lake

\`\`\`bash
curl http://localhost:${hostPort}/tables -H "x-api-key: $(grep -E '^API_KEYS=' .env | cut -d= -f2 | cut -d, -f1 | tr -d '\\"')"
\`\`\`

Tables created from any other gateway on the LAN should appear here.
`;

    const files = [];
    files.push(await writeOutput(outDir, 'compose.yaml',        compose));
    files.push(await writeOutput(outDir, 'setup-nfs-client.sh', setupNfs, { executable: true }));
    files.push(await writeOutput(outDir, '.env',                envBody));
    files.push(await writeOutput(outDir, 'README.md',           readme));

    return {
        outDir, files,
        nextSteps: [
            `cd ${outDir.rel}`,
            'sudo ./setup-nfs-client.sh',
            'docker compose up -d --build',
            `Then hit http://localhost:${hostPort}`,
        ],
    };
}
